# Taken from https://github.com/kikito/middleclass/blob/master/.travis.yml
os: linux
language: python
sudo: false

addons:
  apt:
    packages:
      - libev-dev
      - nginx-extras

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

matrix:
  allow_failures:
    - env: LUA="lua=5.3"

before_install:
  - pip install hererocks
  - hererocks lua_nginx   -r^ --lua=5.1
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - $PWD/lua_nginx/bin/luarocks --tree=$PWD/lua_install install compat52
  - $PWD/lua_nginx/bin/luarocks --tree=$PWD/lua_install install lua-cjson
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install coronest
  - luarocks make rockspec/hotswap-master-1.rockspec
  - for file in rockspec/hotswap-*-master-1.rockspec; do luarocks make $file; done

script:
  - luacheck --std max+busted src/hotswap/*.lua
  - busted --verbose --coverage --pattern=test test

after_success:
  - luacov-coveralls --exclude "test" --exclude "lua_install"

notifications:
  recipients:
    - alban@linard.fr
  email:
    on_success: change
    on_failure: always
